[mgr]
sort_by = "natural"
sort_dir_first = true
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
title_format = "Yazi: {cwd}"

[opener]
image = [
  { run = 'loupe "$@"', desc = "Open image files with Loupe" },
  { run = 'nomacs "$@"', desc = "Open image files with Nomacs" }
]

video = [
  { run = 'mpv "$@"', desc = "Open video files with MPV" },
]

pdf = [
  { run = 'firefox --new-window "$@"', desc = "Open PDF files with Firefox" },
]

[open]
rules = [
  { url = "*.png", use = "image" },
  { url = "*.jpg", use = "image" },
  { url = "*.jpeg", use = "image" },
  { url = "*.bmp", use = "image" },
  { url = "*.webp", use = "image" },
  { url = "*.tiff", use = "image" },

  { url = "*.mp4", use = "video" },
  { url = "*.mkv", use = "video" },
  { url = "*.avi", use = "video" },
  { url = "*.webm", use = "video" },

  { url = "*.pdf", use = "pdf" },
]
